n=[20,30,50,90,60,80,70]
print(n)
n.append(40)
print("append 40 at the end:",n)
n.extend([90,10,60])
print("extend with new list:",n)
n.insert(3,20)
print("insert 20 at 3rd index:",n)
n.remove(90)
print("remove first occurrence:", n)
n.pop(0)
print("pop(remove) the number at specific index:",n)
n.sort()
print("sort:",n)
n.reverse()
print("reverse:",n)
n.count(60)
print("count the number:",n)
print("index of number:",n.index(60))
print("max number:",max(n))
print("min number:",min(n))

